### PR TITLE
Fix #6190: sphinxcontrib-websupport doesn't work with Sphinx 2.0.0b1

### PR DESCRIPTION
**Pull request by tk0miya**
refs: https://github.com/sphinx-doc/sphinx/issues/6190

### CODE REVIEW

**Comment by hroncok** [comment]
Thank You.

**Comment by hroncok** [comment]
@tk0miya May I kindly ask for a beta release? So it is possible to pip install --pre this together with Sphinx 2.0.0b1.

**Comment by tk0miya** [comment]
I just released v1.1.1 including this now!

**Comment by hroncok** [comment]
Thanks :tada: :balloon:

**Pull request merged**
